### ISSUE TITLE
Request: Command to add money/xp.

### ISSUE THREAD

**Issue by Xeddius** [MerryMaw/maw_basewars_2017#1]
I would like if possible to add a command for adding Money/XP and a config for setting an initial amount of money.

ULX integration would be a fantastic addition as well.

**Comment by MerryMaw** [comment]
ULX is an addon and should be treated as such. The gamemode follows the rules of isAdmin(). It was designed to work out of the box without the need of addons. "Integrating" ULX would mean the gamemode now requires ULX, which is not the intention, however you should be able to run ULX just fine with this gamemode.

For adding money, you can go to the chatcommand.lua under sv_various folder and add your own chatcommands there. You may even add additional features for your community if you so wish to create a new branch from this one if you so desire. :)
